INSERT INTO answers (answer, is_correct) VALUES
  ('Prince', 0),
  ('Elvis Presley', 0),
  ('Michael Jackson', 1),
  ('1960er', 0),
  ('1970er', 1),
  ('1980er', 0),
  ('Klavier', 0),
  ('Flöte', 1),
  ('Geige', 0),
  ('Freddie Mercury', 1),
  ('Mick Jagger', 0),
  ('David Bowie', 0),
  ('Rock', 0),
  ('Jazz', 1),
  ('Hip-Hop', 0),
  ('Michael Jackson - "Thriller"', 0),
  ('The Rolling Stones - "Sticky Fingers"', 0),
  ('Billy Joel - "52nd Street"', 1),
  ('Hip-Hop', 1),
  ('Country', 0),
  ('Reggae', 0),
  ('Jimmy Page (Led Zeppelin)', 0),
  ('Jimi Hendrix', 0),
  ('Ritchie Blackmore (Deep Purple)', 1),
  ('Die Zauberflöte', 0),
  ('La Traviata', 1),
  ('Die Meistersinger von Nürnberg', 0),
  ('Klarinette', 1),
  ('Trompete', 0),
  ('Geige', 0),
  ('Quentin Tarantino', 0),
  ('Steven Spielberg', 1),
  ('Martin Scorsese', 0),
  ('The Dark Knight', 1),
  ('Inception', 0),
  ('Brokeback Mountain', 0),
  ('Joker', 0),
  ('1917', 0),
  ('Parasite', 1),
  ('Titanic', 1),
  ('Avatar', 0),
  ('Terminator 2: Judgment Day', 0),
  ('Chris Evans', 0),
  ('Chris Hemsworth', 0),
  ('Robert Downey Jr.', 1),
  ('Bruce', 1),
  ('Jaws', 0),
  ('Moby', 0),
  ('Orlando Bloom', 0),
  ('Elijah Wood', 1),
  ('Sean Connery', 0),
  ('Reservoir Dogs', 1),
  ('Pulp Fiction', 0),
  ('Jackie Brown', 0),
  ('1977', 1),
  ('1983', 0),
  ('1990', 0),
  ('Christopher Nolan', 1),
  ('David Fincher', 0),
  ('Ridley Scott', 0);


INSERT INTO answers (answer, is_correct, question_id) VALUES
  ('Prince', 0, 1),
  ('Elvis Presley', 0, 1),
  ('Michael Jackson', 1, 1),
  ('1960er', 0, 2),
  ('1970er', 1, 2),
  ('1980er', 0, 2),
  ('Klavier', 0, 3),
  ('Flöte', 1, 3),
  ('Geige', 0, 3),
  ('Freddie Mercury', 1, 4),
  ('Mick Jagger', 0, 4),
  ('David Bowie', 0, 4),
  ('Rock', 0, 5),
  ('Jazz', 1, 5),
  ('Hip-Hop', 0, 5),
  ('Michael Jackson - "Thriller"', 0, 6),
  ('The Rolling Stones - "Sticky Fingers"', 0, 6),
  ('Billy Joel - "52nd Street"', 1, 6),
  ('Hip-Hop', 1, 7),
  ('Country', 0, 7),
  ('Reggae', 0, 7),
  ('Jimmy Page (Led Zeppelin)', 0, 8),
  ('Jimi Hendrix', 0, 8),
  ('Ritchie Blackmore (Deep Purple)', 1, 8),
  ('Die Zauberflöte', 0, 9),
  ('La Traviata', 1, 9),
  ('Die Meistersinger von Nürnberg', 0, 9),
  ('Klarinette', 1, 10),
  ('Trompete', 0, 10),
  ('Geige', 0, 10),
  ('Quentin Tarantino', 0, 11),
  ('Steven Spielberg', 1, 11),
  ('Martin Scorsese', 0, 11),
  ('The Dark Knight', 1, 12),
  ('Inception', 0, 12),
  ('Brokeback Mountain', 0, 12),
  ('Joker', 0, 13),
  ('1917', 0, 13),
  ('Parasite', 1, 13),
  ('Titanic', 1, 14),
  ('Avatar', 0, 14),
  ('Terminator 2: Judgment Day', 0, 14),
  ('Chris Evans', 0, 15),
  ('Chris Hemsworth', 0, 15),
  ('Robert Downey Jr.', 1, 15),
  ('Bruce', 1, 16),
  ('Jaws', 0, 16),
  ('Moby', 0, 16),
  ('Orlando Bloom', 0, 17),
  ('Elijah Wood', 1, 17),
  ('Sean Connery', 0, 17),
  ('Reservoir Dogs', 1, 18),
  ('Pulp Fiction', 0, 18),
  ('Jackie Brown', 0, 18),
  ('1977', 1, 19),
  ('1983', 0, 19),
  ('1990', 0, 19),
  ('Christopher Nolan', 1, 20),
  ('David Fincher', 0, 20),
  ('Ridley Scott', 0, 20);
