INSERT INTO questions (question, topic) VALUES
  ('Welcher dieser Künstler ist als "King of Pop" bekannt?', 'MUSIC'),
  ('In welchem Jahrzehnt erlebte die Disco-Musik ihre Blütezeit?', 'MUSIC'),
  ('Welches Instrument spielt der Protagonist in der berühmten Mozart-Oper "Die Zauberflöte"?', 'MUSIC'),
  ('Wer ist der Leadsänger der Band "Queen"?', 'MUSIC'),
  ('Welches Genre ist mit Künstlern wie John Coltrane und Miles Davis verbunden?', 'MUSIC'),
  ('Welches Album wurde als erstes auf CD veröffentlicht?', 'MUSIC'),
  ('Welche Musikrichtung ist eng mit dem New Yorker Stadtteil Bronx verbunden?', 'MUSIC'),
  ('Wer ist für das berühmte Gitarrenriff in "Smoke on the Water" verantwortlich?', 'MUSIC'),
  ('Welche Oper wurde von Giuseppe Verdi komponiert?', 'MUSIC'),
  ('Welches dieser Musikinstrumente gehört zur Familie der Holzblasinstrumente?', 'MUSIC'),
  ('Wer führte Regie bei "Forrest Gump"?', 'MOVIES'),
  ('In welchem Film spielte Heath Ledger die ikonische Rolle des Jokers?', 'MOVIES'),
  ('Welcher Film gewann den Oscar für den besten Film im Jahr 2020?', 'MOVIES'),
  ('In welchem James Cameron Film spielt Leonardo DiCaprio die Hauptrolle?', 'MOVIES'),
  ('Welcher Schauspieler porträtiert den Charakter Iron Man im Marvel Cinematic Universe?', 'MOVIES'),
  ('Was ist der Name des weißen Hais im Film "Der Weiße Hai"?', 'MOVIES'),
  ('Wer spielte die Hauptrolle in der Trilogie "Der Herr der Ringe"?', 'MOVIES'),
  ('Welcher Film wurde von Quentin Tarantino inszeniert und handelt von einer Gruppe von Verbrechern, die einen Diamantenraub planen?', 'MOVIES'),
  ('In welchem Jahr wurde der erste Star Wars Film veröffentlicht?', 'MOVIES'),
  ('Wer ist der Regisseur des Films "Inception"?', 'MOVIES');
